# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xGgWOLRMx4H7QjyroO3c6t_PRPDEF9bp
"""

n=int(input("Enter Number"))#soln 1
for i in range(n):
  for j in range(i):
    print("*",end=" ")
  print("\n")
for i in range(n,0,-1):
  for j in range(i):
    print("*",end=" ")
  print('\n')

n=input("Enter word")# soln 2
ab=n[::-1]
print(ab)